global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "doc-api"
    static_configs:
      - targets: ["api:8000"]
  - job_name: "doc-worker"
    static_configs:
      - targets: ["worker:9002"]